"""Add instituicao and contato to User

Revision ID: b41aefb56077
Revises: d17c5843d471
Create Date: 2025-11-13 10:45:39.738395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41aefb56077'
down_revision = 'd17c5843d471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contato', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contato')
        batch_op.drop_column('instituicao')

    # ### end Alembic commands ###
