"""add featured_image to posts

Revision ID: d17c5843d471
Revises: 4e2f72be1cd2
Create Date: 2025-11-10 13:34:53.505465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17c5843d471'
down_revision = '4e2f72be1cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###
